substitutions:
  _REGION: "asia-southeast2"
  _REPO: "prosperal-artifacts"
  _IMAGE_NAME: "inference-job"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE_NAME:$SHORT_SHA"
      - "-f"
      - "job/Dockerfile"
      - "job"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE_NAME:$SHORT_SHA"

images:
  - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE_NAME:$SHORT_SHA"
